### ISSUE TITLE
Figure Permissions JATS importer/exporter

### ISSUE THREAD

**Issue by michael** [substance/texture#697]
Write converters to store figure permission information:

TextureJATS serialisation:

```xml
<permissions>
 <copyright-statement>© 2014 Surname et al.</copyright-statement>
 <copyright-year>2014</copyright-year>
 <copyright-holder>Surname et al.</copyright-holder>
 <license>
 <ali:license_ref>http://creativecommons.org/licenses/by/4.0/</ali:license_ref>
 <license-p>This is an open access article distributed under the terms of the <ext-link
 ext-link-type="uri" xlink:href="http://creativecommons.org/licenses/by/4.0/">Creative
 Commons Attribution License</ext-link>, which permits unrestricted use, distribution,
 reproduction and adaptation in any medium and for any purpose provided that it is properly
 attributed. For attribution, the original author(s), title, publication source (PeerJ) and
 either DOI or URL of the article must be cited.</license-p>
 </license>
</permissions>
```

Steps:

- [ ] add permissions to figure in kitchen sink
- [ ] adjust TextureJATS.rng to support those elements
- [ ] write converter

**Comment by michael** [comment]
Using `<ali:license>` for some reason breaks the XML parsing so i'm using `<license xlink:href="http://creativecommons.org/licenses/by/4.0/">` instead.

**Comment by michael** [comment]
Fixed via #705

**Comment by oliver----** [comment]
@michael Please make it pass the Persistence test.

> Using <ali:license> for some reason breaks the XML parsing so i'm using <license xlink:href="http://creativecommons.org/licenses/by/4.0/"> instead.

I don't know exactly. Is this really a valid decision. I mean, is there an agreed JATS guide-line already?
If `<ali:license>` can't be parsed, then maybe be beause you forgot to introduce the ns in the XML?
Using namespaces is definitely possible.

**Comment by Melissa37** [comment]
https://jats4r.org/permissions
For JATS version 1.1d3 and forward, the license URI should be contained within<ali:license_ref>. 

What version of JATS are you validating against?

**Comment by oliver----** [comment]
@Melissa37 Thanks. We gonna follow these guide-lines.

I guess the problem here was that in the XML you need to introduce the namespaces, e.g. `ali` on the `<article>` element, which does not seem to be the case in our `kitchen_sink.xml`.

**Comment by Melissa37** [comment]
Ah yes, that's it! It needs the namespace and cannot be before version 1.1d3 of the DTD - forgot the first bit!

**Comment by michael** [comment]
Solved using ali:license_ref conforming to JATS4R. See #752
